//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class KpiInstance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KpiInstance()
        {
            this.KpiDefinitions = new HashSet<KpiDefinition>();
        }
    
        public System.Guid Oid { get; set; }
        public Nullable<System.DateTime> ForceMeasurementDateTime { get; set; }
        public Nullable<System.Guid> KpiDefinition { get; set; }
        public string Settings { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KpiDefinition> KpiDefinitions { get; set; }
        public virtual KpiDefinition KpiDefinition1 { get; set; }
    }
}
