//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SUPPLIERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SUPPLIERS()
        {
            this.TB_BUY = new HashSet<TB_BUY>();
            this.TBL_SuppliersPayments = new HashSet<TBL_SuppliersPayments>();
        }
    
        public int ID { get; set; }
        public string SupplierName { get; set; }
        public Nullable<long> SupplierPhone { get; set; }
        public string SupplierAddress { get; set; }
        public Nullable<System.DateTime> SupplierDate { get; set; }
        public Nullable<double> SupplierBalance { get; set; }
        public Nullable<double> SupplierBalancePrim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BUY> TB_BUY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SuppliersPayments> TBL_SuppliersPayments { get; set; }
    }
}
