//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GREIVANCES
    {
        public int GREIVANCE_ID { get; set; }
        public Nullable<System.DateTime> GREIVANCE_DATE { get; set; }
        public Nullable<int> MARK_ID { get; set; }
        public string NOTE { get; set; }
        public Nullable<bool> STATE { get; set; }
        public Nullable<double> PRICE { get; set; }
    
        public virtual TBL_MARKS TBL_MARKS { get; set; }
    }
}
