//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SIRYAL_STUDENTS
    {
        public int SIRYAL_ID { get; set; }
        public Nullable<int> STUD_ID { get; set; }
        public Nullable<int> SPIC_ID { get; set; }
        public Nullable<int> SIRYAL_YEARS { get; set; }
        public Nullable<decimal> SIRYAL_NUMBER { get; set; }
    
        public virtual TBL_SPECIAL TBL_SPECIAL { get; set; }
        public virtual TBL_STUDENTS TBL_STUDENTS { get; set; }
        public virtual TBL_YEARS_MARK TBL_YEARS_MARK { get; set; }
    }
}
