//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SuppliersPayments
    {
        public int ID { get; set; }
        public Nullable<int> SUPLAYER_ID { get; set; }
        public Nullable<double> Pamnent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual TBL_SUPPLIERS TBL_SUPPLIERS { get; set; }
    }
}
