//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YEARS_MARK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YEARS_MARK()
        {
            this.TBL_MARKS = new HashSet<TBL_MARKS>();
            this.TBL_SIRYAL_STUDENTS = new HashSet<TBL_SIRYAL_STUDENTS>();
        }
    
        public int ID { get; set; }
        public string YEARS_NAME { get; set; }
        public string YEARS_DATA { get; set; }
        public Nullable<bool> STATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MARKS> TBL_MARKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SIRYAL_STUDENTS> TBL_SIRYAL_STUDENTS { get; set; }
    }
}
