//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THAGBAN_INST.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BOX
    {
        public int BOX_ID { get; set; }
        public string BOX_AMOUNT { get; set; }
        public Nullable<int> INST_ID { get; set; }
    
        public virtual TBL_INST TBL_INST { get; set; }
    }
}
