using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THAGBAN_INST.DATA;
using System.Data.Entity.Migrations;

namespace THAGBAN_INST.FORM.FRM_CONTORL.siryal_number
{
    public partial class FRM_YEARS_MARK_MANG : DevExpress.XtraEditors.XtraUserControl
    {
        int years_id = 0;
        db_max_instEntities con = new DATA.db_max_instEntities();
        bool state = true;
        string years_date = "";
        public FRM_YEARS_MARK_MANG()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            get_data();
            clear();



           
        }
        void get_data()
        { // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_YEARS_MARK.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TBL_YEARS_MARK.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            clear();
        }
        void clear()
        {
            years_id = 0;
            txt_years_name.Text = "";
            txt_years.Text = "";
        }
        private void btn_save_Click(object sender, EventArgs e)
        {
            if (txt_years_name.Text != "")
            {

                try
                {
                    if (txt_years.Text != "" && txt_years_name.Text != "")
                    {


                        TBL_YEARS_MARK years = new TBL_YEARS_MARK();
                        DateTime aa = DateTime.Parse(string.Format("{0:yyyy}", txt_years.Text));
                        years.YEARS_DATA = aa.Year.ToString();
                        years.YEARS_NAME = txt_years_name.Text;
                       
                        years.STATE = state;
                       
                        
                                
                        con.TBL_YEARS_MARK.AddOrUpdate(years);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                        notifiction.Show();
                        get_data();
                        clear();
                    }
                }
                catch(Exception ex)
                {

                }
            }

        }

        private void btn_edite_Click(object sender, EventArgs e)
        {

            try
            {


                TBL_YEARS_MARK years = new TBL_YEARS_MARK();
               // get_select();
                DateTime aa = DateTime.Parse(string.Format("{0:yyyy}", txt_years.Text.ToString()));
                years.ID = years_id;
                years.YEARS_DATA = years_date;
                years.YEARS_NAME = txt_years_name.Text;
               
                years.STATE = state;
                
                con.TBL_YEARS_MARK.AddOrUpdate(years);
                con.SaveChanges();
                adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.AddNotificationText, THAGBAN_INST.Properties.Resources.add_32px);
                notifiction.Show();
                get_data();
                clear();
            }
            catch(Exception ex)
            {
                MessageBox.Show(ex.Message + ex.InnerException);
            }

        }
        void get_select()
        {
            if (gridView2.RowCount > 1 )
            {
                try
                {
                    years_id = Convert.ToInt32(gridView2.GetFocusedRowCellValue("ID").ToString());
                    txt_years_name.Text = gridView2.GetFocusedRowCellValue("YEARS_NAME").ToString();
                    //  txt_years.Text=string.Format("{0:yyyy}", gridView2.GetFocusedRowCellValue("YEARS_DATA").ToString());


                    txt_years.Text = gridView2.GetFocusedRowCellValue("YEARS_DATA").ToString();

                    state = (bool)gridView2.GetFocusedRowCellValue("STATE");
                    if (state==true)
                    {
                        rdb_open.Checked = true;
                    }
                    else
                    {
                        rdb_close.Checked = true;
                    }
                }
                catch (Exception)
                {

                }
               
            }
        }

        private void gridView2_SelectionChanged(object sender, DevExpress.Data.SelectionChangedEventArgs e)
        {
           get_select();
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            delete();
        }
        void delete()
        {
            if (years_id != 0)
            {
                try
                {
                    DialogResult res = MessageBox.Show("هل تريد تاكيد الحذف ", "تحذير الحذف ", MessageBoxButtons.OKCancel, MessageBoxIcon.Error);
                    if (res == DialogResult.OK)
                    {
                        TBL_YEARS_MARK del_cle = con.TBL_YEARS_MARK.Find(years_id);
                        // del_doc.DOC_ID = holiday_type_id;

                        con.TBL_YEARS_MARK.Remove(del_cle);
                        con.SaveChanges();
                        adl.NotifictionUser notifiction = new adl.NotifictionUser(THAGBAN_INST.Properties.Resources.DeleteNotificationText, THAGBAN_INST.Properties.Resources.Delete_32px);
                        notifiction.Show();
                    }
                }
                catch (Exception ex) { }
                get_data();
                clear();
            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            get_data();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void gridView2_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {

        }

        private void rdb_close_CheckedChanged(object sender, EventArgs e)
        {
            if (rdb_close.Checked == true)
                state = false;
            else
                state = true;
        }

        private void rdb_open_CheckedChanged(object sender, EventArgs e)
        {
            if (rdb_open.Checked == true)
                state = true;
            else
                state = false;
        }

        private void txt_years_EditValueChanged(object sender, EventArgs e)
        {
            try
            {
                DateTime aa = DateTime.Parse(string.Format("{0:yyyy}", txt_years.Text.ToString()));

                years_date = aa.Year.ToString();
            }
            catch(Exception ex) { 
            }
        }
    }
}