using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using THAGBAN_INST.DATA;
using DevExpress.XtraCharts.Native;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Button;

namespace THAGBAN_INST.FORM.FRM_CONTORL
{
    public partial class analys_control_admin : DevExpress.XtraEditors.XtraUserControl
    {
        private int lect_id;
        db_max_instEntities con = new db_max_instEntities();
        private int tech_lect_id;
        string courne1 = THAGBAN_INST.Properties.Settings.Default.courncy;
        private int? spec_id;
        private int? years_id;

        public analys_control_admin()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            get_data();
            load_good_pad();
            chek_Change();
            //load_send_rest();
            //cheack_change();
            //Get_piad();
            //get_seles();

            load_good_pad();





        }

        void get_data()
        {// This line of code is generated by Data Source Configuration Wizard



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            THAGBAN_INST.DATA.db_max_instEntities dbContext = new THAGBAN_INST.DATA.db_max_instEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TBL_MARKS.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                chartControl1.DataSource = dbContext.TBL_MARKS.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext()); 

            // load spic
            com_spic.DataSource=con.TBL_STUD_SPEC.Join(con.TBL_SPECIAL,sp=>sp.TBL_SPECIAL.SPEC_ID,st=>st.SPEC_ID,
            (spic,std)=> new  
            {
            std.SPEC_ID,
            std.SPEC_NAME
            }).Distinct().ToList();
            com_spic.DisplayMember = "SPEC_NAME";
            com_spic.ValueMember = "SPEC_ID";

            com_years.DataSource=con.TBL_YEARS_MARK.ToList();
            com_years.DisplayMember = "YEARS_DATA";
            com_years.ValueMember="ID";



        }
        private void load_good_pad()
        {
            try
            {
                db_max_instEntities db = new db_max_instEntities();

                var goodCount = db.TBL_MARKS
                    .GroupBy(grp => new { grp.STUD_ID, grp.TBL_SPECIAL.SPEC_NAME })
                    .Where(x => x.Min(w => w.MARK_COURS) > 50)
                    .Count();

                var padCount = db.TBL_MARKS
                    .GroupBy(grp => new { grp.STUD_ID, grp.TBL_SPECIAL.SPEC_NAME })
                    .Where(x => x.Count(w => w.MARK_COURS <= 50) >= 3)
                    .Count();

                lbl_good_y1.Text = goodCount.ToString() + "   ";
                lbl_pad.Text = padCount.ToString() + "   ";
            }
            catch { }
        }



        private void load_good_pad_serch_spec()
        {
            try
            {

                db_max_instEntities db = new db_max_instEntities();
                lbl_good_y1.Text = db.TBL_MARKS.Where(w=>w.SPEC_ID==spec_id).GroupBy(
                    grp => new { grp.STUD_ID, grp.TBL_SPECIAL.SPEC_NAME }
                    ).Where(
                    x => x.Min(w => w.MARK_COURS) >= 50 ).Count().ToString() + "   ";
                lbl_pad.Text = db.TBL_MARKS.Where(w => w.SPEC_ID == spec_id).GroupBy(
                    grp => new { grp.STUD_ID, grp.TBL_SPECIAL.SPEC_NAME }
                    ).Where(x => x.Count(w => w.MARK_COURS <= 50) >= 3).Count().ToString() + "   ";
                // value.ToString("#0.00") + "   " + curr2;

                chartControl1.DataSource = con.TBL_MARKS.Where(w => w.SPEC_ID == spec_id).ToList();
            }
            catch { }
        }

        private void load_good_pad_serch_spec_years()
        {
            try
            {

                db_max_instEntities db = new db_max_instEntities();
                lbl_good_y1.Text = db.TBL_MARKS.Where(w => w.SPEC_ID == spec_id && w.YEARS_ID==years_id).GroupBy(
                    grp => new { grp.STUD_ID, grp.TBL_SPECIAL.SPEC_NAME }
                    ).Where(
                    x => x.Min(w => w.MARK_COURS) >= 50).Count().ToString() + "   ";
                lbl_pad.Text = db.TBL_MARKS.Where(w => w.SPEC_ID == spec_id && w.YEARS_ID == years_id).GroupBy(
                    grp => new { grp.STUD_ID, grp.TBL_SPECIAL.SPEC_NAME }
                    ).Where(x => x.Count(w => w.MARK_COURS <= 50) >= 3).Count().ToString() + "   ";
                // value.ToString("#0.00") + "   " + curr2;
                chartControl1.DataSource = con.TBL_MARKS.Where(w => w.SPEC_ID == spec_id && w.YEARS_ID==years_id).ToList();


            }
            catch { }
        }

        private void label4_Click(object sender, EventArgs e)
        {

        }

        private void flowLayoutPanel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            load_good_pad();
           
            get_data();
            load_good_pad();

        }
        void get_first()
        {

        }

        private void com_lect_SelectedIndexChanged(object sender, EventArgs e)
        {
            //get_group();
            //Get_piad();
        }

        private void com_group_SelectedIndexChanged(object sender, EventArgs e)
        {
           // get_group();
          //  Get_piad();
        }

        private void ch_lect_CheckedChanged(object sender, EventArgs e)
        {
            //cheack_change();
            //get_lect();
            //Get_piad();
        }

        private void ch_grou_CheckedChanged(object sender, EventArgs e)
        {
            //cheack_change();
            //get_group();
            //Get_piad();
            //get_seles();
        }

        private void flowLayoutPanel1_Paint_1(object sender, PaintEventArgs e)
        {

        }

        private void panel7_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label7_Click(object sender, EventArgs e)
        {

        }

        private void lb_buy1_Click(object sender, EventArgs e)
        {

        }

        private void panel8_Paint(object sender, PaintEventArgs e)
        {

        }

        private void lb_buy2_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox3_Click(object sender, EventArgs e)
        {

        }

        private void label4_Click_1(object sender, EventArgs e)
        {

        }

        private void lbl_good1_Click(object sender, EventArgs e)
        {

        }

        private void panel6_Paint(object sender, PaintEventArgs e)
        {

        }

        private void panel9_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label10_Click(object sender, EventArgs e)
        {

        }

        private void lb_sell1_Click(object sender, EventArgs e)
        {

        }

        private void panel10_Paint(object sender, PaintEventArgs e)
        {

        }

        private void lb_sell2_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox4_Click(object sender, EventArgs e)
        {

        }

        private void panel11_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label13_Click(object sender, EventArgs e)
        {

        }

        private void lb_benfit1_Click(object sender, EventArgs e)
        {

        }

        private void panel12_Paint(object sender, PaintEventArgs e)
        {

        }

        private void lb_benfit2_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox5_Click(object sender, EventArgs e)
        {

        }

        private void panel13_Paint(object sender, PaintEventArgs e)
        {

        }

        private void chartControl1_Click(object sender, EventArgs e)
        {

        }

        private void panel3_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void btn_add_Click_1(object sender, EventArgs e)
        {
            get_data();
            chek_Change();
        }

        private void lbl_good2_Click(object sender, EventArgs e)
        {

        }

        private void lbl_rest1_Click(object sender, EventArgs e)
        {

        }

        private void panel14_Paint(object sender, PaintEventArgs e)
        {

        }

        private void ch_grou_CheckedChanged_1(object sender, EventArgs e)
        {

        }

        private void ch_lect_CheckedChanged_1(object sender, EventArgs e)
        {
            chek_Change();
        }
        void chek_Change()
        {

            if (ch_spec.Checked == true)
            {
                com_spic.Enabled = true;
                load_good_pad_serch_spec();
            }
            else
            {
                com_spic.Enabled = false;
                load_good_pad();
            }
            if (ch_years.Checked == true)
            {
                com_years.Enabled = true;
                load_good_pad_serch_spec_years();
            }
            else
            {
                com_years.Enabled = false;
                load_good_pad();
            }

        }
        private void com_group_SelectedIndexChanged_1(object sender, EventArgs e)
        {

        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void lbl_pad1_Click(object sender, EventArgs e)
        {

        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void panel4_Paint(object sender, PaintEventArgs e)
        {

        }

        private void lbl_rest2_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox2_Click(object sender, EventArgs e)
        {

        }

        private void panel15_Paint(object sender, PaintEventArgs e)
        {

        }

        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void com_lect_SelectedIndexChanged_1(object sender, EventArgs e)
        {
            try
            {
                spec_id = Convert.ToInt32(com_spic.SelectedValue.ToString());
                load_good_pad_serch_spec();

            }catch(Exception ex)
            {

            }
        }

        private void panel16_Paint(object sender, PaintEventArgs e)
        {

        }

        private void lbl_pad2_Click(object sender, EventArgs e)
        {

        }

        private void pictureBox6_Click(object sender, EventArgs e)
        {

        }

        private void panel5_Paint(object sender, PaintEventArgs e)
        {

        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {

        }

        private void ch_years_CheckedChanged(object sender, EventArgs e)
        {
            chek_Change();
        }

        private void com_years_SelectedIndexChanged(object sender, EventArgs e)
        {
            try
            {
                years_id = Convert.ToInt32(com_years.SelectedValue.ToString());
                load_good_pad_serch_spec_years();

            }
            catch (Exception ex)
            {

            }
        }
    }
}
